export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
export const SELECT_REMINDERS = 'SELECT_REMINDERS';
export const DELETE_SELECTS = 'DELETE_SELECTS';